<?php
/*error_reporting(E_ALL);
ini_set('display_errors', TRUE);
ini_set('display_startup_errors', TRUE);*/
ini_set('memory_limit', '-1');
global $base_url; // Will point to http://www.example.com

function view_responses_all() {
  // Initialize output
//$output = '';
  // Query the database for all responses
  $query = \Drupal::database()->select('installer_response', 'ir');
  $query->fields('ir');
  $results = $query->execute();

  // Prepare rows for the table
  $preference_rows = [];
  while ($row = $results->fetchObject())
  {
    $preference_rows[$row->id] = [
        $row->id,
        $row->name_title . '. ' . $row->first_name . ' ' . $row->last_name,
        $row->institute,
        $row->email_id,
        $row->designation
      ];
  }

  // Define table headers
  $preference_header = [
    'S.No',
    'Name',
    'Institute',
    'Email ID',
    'Designation'
  ];

  // Build the table render array
  $output = [
    '#type' => 'table',
    '#header' => $preference_header,
    '#rows' => $preference_rows
  ];
  return $output;
}
function installer_directory_path() {
  // Get the base path for the installation directory.
  $base_path = \Drupal::service('file_system')->realpath('public://osdag/installers/');

  // Ensure the directory exists
  if (is_dir($base_path)) {
    return $base_path;
  }

  // If directory doesn't exist, return an empty string or handle error appropriately
  return '';
}